// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package authors_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int32
	Name string
	Bio  pgtype.Text
}

type Book struct {
	ID       int32
	AuthorID int32
	Name     string
	Summary  pgtype.Text
}
